sudo: true

language: go

# Using version installed on computer
go:
- 1.11.4

# Probably not used
go_import_path: github.com/pkg/foo

before_install:
  - sudo apt-get update
  - sudo apt install -y libc6-dev libglu1-mesa-dev libgles2-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev
before_script:
  # Get Gopherjs
  - go get -u github.com/gopherjs/gopherjs
  - go get -u github.com/gopherjs/gopherwasm/js
script:
  - gopherjs build -o spaceshooter.js github.com/FriendlyUser/spaceshooter

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: .
  github-token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - "web/spaceshooter.js"
    - "web/index.html"
  skip_cleanup: true
  on:
    tags: true