sudo: true

language: go

# Using version installed on computer
go:
- 1.11.4

# Probably not used
go_import_path: github.com/pkg/foo

before_script:
  - sudo apt install -y libc6-dev libglu1-mesa-dev libgles2-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev
  # Golang Dependencies
  - go get ./...
  # Gopherjs
script:
  - gopherjs build -o spaceshooter.js github.com/FriendlyUser/spaceshooter

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - "spaceshooter.js"
    - "index.html"
  skip_cleanup: true
  on:
    tags: true